### ISSUE TITLE
d label not working properly

### ISSUE THREAD

**Issue by Skuzzzy** [joowani/dtags#6] opened 2016-03-05 22:30 UTC
http://i.imgur.com/MoZfuFf.png

See picture.

**Comment by joowani** [comment] 2016-03-05 22:46
Hi Skuzzy,

Unforunately, I am unable to reproduce the issue.
Could you please provide me with the following details:

1. python version
2. shell in use (bash/zsh/fish)
3. is this only happening for that particular tag/directory?
4. do you have "test" aliased to something?

Thanks

**Comment by Skuzzzy** [comment] 2016-03-05 23:14
1. python 2.7.6 + pip 1.5.4
2. zsh
3. All directories, all tags http://i.imgur.com/Bnvim6m.png
4. Test was aliased to something, so I used a different tag in the following example.

http://i.imgur.com/4cRkoxy.png

**Comment by joowani** [comment] 2016-03-05 23:17
Hi Skuzzy,

Np, thanks for the bug report.
Could you check if the `d` itself is aliased to something?
Perhaps something like `alias d="d -10 ..."`?

**Comment by Skuzzzy** [comment] 2016-03-05 23:21
d is not aliased to anything
dan@dan-desktop:/home/dan/dtags  git:(master) $ alias | grep d=
afind='ack -il'
d='dirs -v | head -10'
gd='git diff'
gignored='git ls-files -v | grep "^[[:lower:]]"'
gpd='git push --dry-run'
gsd='git svn dcommit'
gstd='git stash drop'
md='mkdir -p'
rd=rmdir
which-command=whence


I ran the unit tests for the project on my machine and some failed, I have attached a log. I have not examined it yet just ran them a few seconds ago.
http://pastebin.com/s6wYRCfM

**Comment by Skuzzzy** [comment] 2016-03-05 23:24
The tests are not very granular, so it's hard to see the full range of what is breaking. I do not have fish installed, but it seems like most of the tests are breaking in d.

**Comment by Skuzzzy** [comment] 2016-03-05 23:29
How would I run this manually, I want to step through the d command with a debugger. What command would I execute to do this?

**Comment by joowani** [comment] 2016-03-05 23:31
Yea... don't worry too much about the tests. It IS very crude at the moment. I only put it in there mostly for my own internal testing so I don't expect the tests to succeed on other machines (I will keep this im mind and improve it in the future). Other than the errors on `d`, however, the errors don't seem too concerning. Just to triple check could you please try running `which d`? thx

**Comment by joowani** [comment] 2016-03-05 23:32
Try running `dtags shell zsh`. The output of that is what is sourced to define function d.

**Comment by Skuzzzy** [comment] 2016-03-05 23:33
Actually looks like I have d aliased to something... now I feel like an idiot.

**Comment by joowani** [comment] 2016-03-05 23:34
Awesome! Glad we could solve the issue :) 
Closing issue. Thanks for trying out dtags.

**Closed** 2016-03-05 23:35 UTC
